# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6821aa827ba74f9d51d5e4c38cefc41b2f868184d66a534eea6d9c08c698bd066df62475eb18023f34554423bd166be300d47016f54a7175701ba346ed18e618

test:
  secret_key_base: 40347a58a332c3e528db8ce115d894e3891677ecc8397a84445b44d1e87f7ca454418f4fbf2b747b0ba576a9ccd67ba997ce748e8b003ce2f30ad4140f1a0779

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
